"""Tests for research_companion.report_export — Deep-Research Report
Export (markdown), Phase 2, slice 2e-5.

report_to_markdown(report: dict) -> str is a pure, never-raises serializer:
isinstance-guarded on every nested field, a malformed/partial/None report
degrades to a best-effort (or empty) string rather than raising. The
markdown carries the same honesty caveats the live Report view (views/
report.js) shows -- RCS badges labeled AI judgments, coverage labeled a
BM25 heuristic, per-section unverified-quote callouts -- so an exported/
shared file is no more "verified" than the UI. No new LLM prompt: this is
pure serialization of an already-built report (deep_research.build_report
+ the 2e-2 rcs / 2e-3 coverage / 2e-4 plan additions), never generation.

See docs/superpowers/specs/2026-08-10-report-export-design.md.
"""
from __future__ import annotations

from research_companion.report_export import report_to_markdown


def _full_report() -> dict:
    return {
        "topic": "graph retrieval",
        "sections": [
            {
                "question": "What methods are used?",
                "answer": "Graph retrieval is used [S1].",
                "citations": [{
                    "paper_id": "arxiv:1234.56789", "paper_title": "Graph Retrieval Paper",
                    "section_id": "s1", "char_start": 0, "char_end": 100,
                    "chunk_index": 0, "score": 2.5,
                    "rcs": {"relevance": 0.8, "stance": "supports",
                            "rationale": "Directly backs the claim."},
                }],
                "unverified_quotes": ["a made-up quote"],
                "coverage": {"pct": 50, "cited": 1, "relevant_available": 2},
            },
            {
                "question": "What datasets are used?",
                "answer": "",
                "citations": [],
                "unverified_quotes": [],
                "error": "No answer was returned for this question.",
            },
        ],
        "generated_from": {}, "question_count": 2,
        "coverage": {"pct": 50, "cited": 1, "relevant_available": 2, "median_pct": 50},
        "coverage_generated_from": "abc123",
    }


# ---------------------------------------------------------------------------
# Full report -> all elements present
# ---------------------------------------------------------------------------

def test_full_report_includes_all_elements():
    md = report_to_markdown(_full_report())
    assert md.startswith("# graph retrieval\n")
    assert "**Coverage:** 50% (median 50%) — 1/2 relevant passages cited" in md
    assert "## What methods are used?" in md
    assert "Graph retrieval is used [S1]." in md
    assert "**Citations**" in md
    assert "Graph Retrieval Paper" in md
    assert "s1, chars 0–100" in md
    assert "_[relevance 80%, supports]_" in md
    assert "_Coverage: 50% (1/2)_" in md
    assert "Unverified quote(s) (not found verbatim in your library): a made-up quote" in md
    assert "## What datasets are used?" in md
    assert "_Error: No answer was returned for this question._" in md
    assert "Relevance & stance are AI judgments of the cited passage" in md
    assert "Coverage is a BM25 heuristic" in md
    assert "Generated by Research Companion" in md


def test_no_topic_falls_back_to_generic_title():
    md = report_to_markdown({"topic": "", "sections": [], "generated_from": {}, "question_count": 0})
    assert md.startswith("# Deep-Research Report\n")


# ---------------------------------------------------------------------------
# Conditional omission -- no rcs / no coverage
# ---------------------------------------------------------------------------

def test_no_rcs_omits_rcs_badge_and_caveat():
    report = _full_report()
    del report["sections"][0]["citations"][0]["rcs"]
    md = report_to_markdown(report)
    assert "_[relevance" not in md
    assert "AI judgments of the cited passage" not in md


def test_no_coverage_omits_coverage_lines_and_caveat():
    report = _full_report()
    del report["coverage"]
    for s in report["sections"]:
        s.pop("coverage", None)
    md = report_to_markdown(report)
    assert "**Coverage:**" not in md
    assert "_Coverage:" not in md
    assert "BM25 heuristic" not in md


def test_no_unverified_quotes_omits_callout():
    report = _full_report()
    report["sections"][0]["unverified_quotes"] = []
    md = report_to_markdown(report)
    assert "Unverified quote" not in md


def test_no_error_omits_error_line():
    report = _full_report()
    del report["sections"][1]["error"]
    md = report_to_markdown(report)
    assert "_Error:" not in md


# ---------------------------------------------------------------------------
# Malformed / partial / None -> never raises, best-effort or empty
# ---------------------------------------------------------------------------

def test_none_report_never_raises_returns_empty_string():
    assert report_to_markdown(None) == ""


def test_non_dict_report_never_raises_returns_empty_string():
    assert report_to_markdown("not a dict") == ""
    assert report_to_markdown(42) == ""
    assert report_to_markdown([]) == ""


def test_empty_dict_report_never_raises():
    md = report_to_markdown({})
    assert md.startswith("# Deep-Research Report")
    assert "Generated by Research Companion" in md


def test_malformed_sections_not_a_list_never_raises():
    md = report_to_markdown({"topic": "t", "sections": "not a list"})
    assert md.startswith("# t")


def test_non_dict_section_is_skipped_never_raises():
    md = report_to_markdown({"topic": "t", "sections": ["not a dict", None, 42]})
    assert md.startswith("# t")
    assert "## " not in md


def test_non_dict_citation_is_skipped_never_raises():
    report = {
        "topic": "t",
        "sections": [{
            "question": "Q?", "answer": "A",
            "citations": ["not a dict", None, {"paper_title": "Real Paper"}],
            "unverified_quotes": [],
        }],
    }
    md = report_to_markdown(report)
    assert "Real Paper" in md
    assert "## Q?" in md


def test_missing_citation_fields_default_safely():
    report = {
        "topic": "t",
        "sections": [{"question": "Q?", "answer": "A", "citations": [{}], "unverified_quotes": []}],
    }
    md = report_to_markdown(report)
    assert "Untitled" in md


def test_malformed_rcs_defaults_safely_never_raises():
    report = {
        "topic": "t",
        "sections": [{
            "question": "Q?", "answer": "A",
            "citations": [{"paper_title": "P", "rcs": {"relevance": "not a number", "stance": "weird"}}],
            "unverified_quotes": [],
        }],
    }
    md = report_to_markdown(report)
    assert "_[relevance 0%, neutral]_" in md


def test_malformed_coverage_field_not_a_dict_is_ignored():
    md = report_to_markdown({"topic": "t", "sections": [], "coverage": "not a dict"})
    assert "**Coverage:**" not in md


def test_no_citations_shows_placeholder_line():
    report = {
        "topic": "t",
        "sections": [{"question": "Q?", "answer": "A", "citations": [], "unverified_quotes": []}],
    }
    md = report_to_markdown(report)
    assert "_No citations._" in md


def test_missing_question_falls_back_to_untitled_question():
    report = {"topic": "t", "sections": [{"answer": "A", "citations": [], "unverified_quotes": []}]}
    md = report_to_markdown(report)
    assert "## Untitled question" in md


def test_empty_sections_list_still_renders_title_and_footer():
    md = report_to_markdown({"topic": "t", "sections": []})
    assert md.startswith("# t")
    assert "Generated by Research Companion" in md
