"""End-to-end test of the REAL offline ingestion spine on a real sample PDF.

No mocks: this walks PDF -> text extraction -> quality gate -> parser
provenance -> section tree -> retrieval units -> BM25 ranking using the actual
parser (pinned to pypdfium by the autouse conftest fixture), the actual
heuristic sectioner, the actual chunker, and the actual BM25 ranker. The goal
is to prove the pipeline works on a realistic digital PDF without stubbing any
of the seams that other, more targeted unit tests exercise in isolation.

The fixture PDF (tests/fixtures/sample_paper.pdf, generated by
tests/fixtures/make_sample_paper.py) has a title line, an Abstract, four
numbered sections (Introduction/Methods/Results/Conclusion) with distinctive
keywords, and a References heading. Assertions below are against the REAL
text pypdfium extracts (verified by probing it directly), not against the
source strings fed to reportlab.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from research_companion import store
from research_companion.extract import pdf_to_text
from research_companion.parsers import get_parser, text_quality
from research_companion.qa import build_section_index
from research_companion.rank import tokenize
from research_companion.retrieve import rank_units
from research_companion.sections import build_and_save_sections

FIXTURE_PDF = Path(__file__).parent / "fixtures" / "sample_paper.pdf"

PAPER_ID = "local:sample"

# Distinctive keywords planted in the fixture's prose, one per section, chosen
# so a BM25 query can target a specific section unambiguously.
METHODS_KEYWORDS = ("BM25", "knowledge graph")
RESULTS_KEYWORDS = ("multi-hop question answering", "SciQA-Mini")
CONCLUSION_KEYWORDS = ("verifiable citations",)


@pytest.fixture
def extracted_text() -> str:
    """Real pdf_to_text() output for the fixture PDF (pypdfium parser)."""
    return pdf_to_text(FIXTURE_PDF)


class TestIngestionEndToEnd:
    """One cohesive walk through the real offline ingestion pipeline."""

    def test_text_extraction(self, extracted_text: str) -> None:
        assert len(extracted_text) > 200
        # Distinctive substrings survive pypdfium extraction verbatim (probed
        # directly against the fixture before writing this assertion).
        assert "BM25" in extracted_text
        assert "knowledge graph" in extracted_text
        assert "SciQA-Mini" in extracted_text
        assert "multi-hop question answering" in extracted_text
        assert "verifiable citations" in extracted_text

    def test_quality_gate_passes(self, extracted_text: str) -> None:
        quality = text_quality(extracted_text)
        assert quality["ok"] is True
        assert quality["char_count"] > 200
        assert quality["alpha_ratio"] >= 0.5

    def test_parser_provenance(self) -> None:
        # conftest pins RESEARCH_COMPANION_PARSER=pypdfium for the whole suite.
        assert get_parser().name == "pypdfium"

    def test_section_tree(self, extracted_text: str) -> None:
        meta = store.PaperMetadata(
            paper_id=PAPER_ID, title="Sample Paper", authors=["A. Researcher"], year=2026
        )
        meta.save()
        store.save_text(PAPER_ID, extracted_text)
        store.save_pdf(PAPER_ID, FIXTURE_PDF.read_bytes())

        sections = build_and_save_sections(PAPER_ID)

        assert len(sections) >= 2
        titles = [s.title for s in sections]
        # The heuristic sectioner strips the leading "N. " numbering, so the
        # real titles it produces are "Introduction", "Methods", etc. (verified
        # by running build_section_tree directly against the extracted text).
        assert any("Introduction" in t for t in titles)
        assert any("Methods" in t for t in titles)
        assert any("Results" in t for t in titles)
        assert any("Conclusion" in t for t in titles)

    def test_retrieval_units(self, extracted_text: str) -> None:
        meta = store.PaperMetadata(
            paper_id=PAPER_ID, title="Sample Paper", authors=["A. Researcher"], year=2026
        )
        meta.save()
        store.save_text(PAPER_ID, extracted_text)
        store.save_pdf(PAPER_ID, FIXTURE_PDF.read_bytes())
        build_and_save_sections(PAPER_ID)

        units = build_section_index([PAPER_ID])

        assert units, "expected at least one retrieval unit"
        required_keys = {"paper_id", "section_id", "char_start", "char_end", "tokens", "text"}
        for unit in units:
            assert required_keys <= set(unit.keys())
            assert unit["char_start"] < unit["char_end"]
            assert unit["char_start"] >= 0
            assert unit["char_end"] <= len(extracted_text)

        concatenated = " ".join(u["text"] for u in units)
        assert "BM25" in concatenated
        assert "knowledge graph" in concatenated
        assert "SciQA-Mini" in concatenated
        assert "verifiable citations" in concatenated

    def test_bm25_ranking_finds_methods_section(self, extracted_text: str) -> None:
        meta = store.PaperMetadata(
            paper_id=PAPER_ID, title="Sample Paper", authors=["A. Researcher"], year=2026
        )
        meta.save()
        store.save_text(PAPER_ID, extracted_text)
        store.save_pdf(PAPER_ID, FIXTURE_PDF.read_bytes())
        build_and_save_sections(PAPER_ID)
        units = build_section_index([PAPER_ID])

        question = "Which ranking method is used for retrieval?"
        q_tokens = tokenize(question)

        # embed_query=None: with no HF_TOKEN configured in the test env,
        # rank_units._auto_embed_query() also resolves to None, so this stays
        # on the pure-BM25 path either way (confirmed: os.environ has no
        # HF_TOKEN under the isolated-env conftest fixture).
        ranked = rank_units(question, q_tokens, units, embed_query=None)

        assert ranked
        top_unit = ranked[0]["unit"]
        assert top_unit["section_id"] == "s3"
        assert "BM25" in top_unit["text"]
