/**
 * claimAuditHelpers.test.mjs — claim-audit wording over the canonical renderer.
 *
 * The rendering must never turn "could not check" into either an accusation or
 * a clean tick.
 *
 * Fixtures are generated by running the real auditor (see
 * fixtures_claim_audit.json), not written by hand. The previous version of this
 * file asserted against `{ outcome, is_adverse }` payloads that the auditor
 * never produces — it always emits a nested `signal` too — so the tests were
 * describing an assumed shape rather than the real one.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..', '..');
const { claimAuditBadge, claimAuditSummaryLine, CLAIM_AUDIT_DISCLAIMER } =
  await import(pathToFileURL(path.join(
    repoRoot, 'research_companion', 'lab', 'static', 'js', 'claimAuditHelpers.js')).href);

const F = JSON.parse(fs.readFileSync(
  path.join(__dirname, 'fixtures_claim_audit.json'), 'utf8'));

const INCONCLUSIVE = ['unverifiable', 'anchorless', 'not_checked'];

test('only not_supported renders as adverse', () => {
  assert.equal(claimAuditBadge(F.not_supported).isAdverse, true);
  for (const key of ['supported', ...INCONCLUSIVE]) {
    assert.equal(claimAuditBadge(F[key]).isAdverse, false, key);
  }
});

test('inconclusive outcomes are muted and never read as supported', () => {
  for (const key of INCONCLUSIVE) {
    const b = claimAuditBadge(F[key]);
    assert.equal(b.tone, 'muted', key);
    assert.doesNotMatch(b.label, /^Supported$/i, key);
  }
});

test('supported and not_supported get distinct tones', () => {
  assert.equal(claimAuditBadge(F.supported).tone, 'ok');
  assert.equal(claimAuditBadge(F.not_supported).tone, 'warn');
});

test('an anchorless citation is distinguishable from an inconclusive one', () => {
  // Both are DEGRADED — each is a failure to check, not a finding — but the
  // user can act on one of them.
  assert.equal(claimAuditBadge(F.anchorless).label, 'No anchor');
  assert.equal(claimAuditBadge(F.unverifiable).label, 'Could not check');
});

test('both directions are labelled an AI judgement, not a fact', () => {
  // The auditor makes one model call; "supported" cannot be a verified fact
  // while "not supported" is merely advisory.
  for (const key of ['supported', 'not_supported']) {
    assert.equal(claimAuditBadge(F[key]).title, CLAIM_AUDIT_DISCLAIMER,
      `${key} must carry the advisory disclaimer`);
  }
});

test('the domain wording is used, not the generic renderer wording', () => {
  assert.equal(claimAuditBadge(F.supported).label, 'Supported');
  assert.equal(claimAuditBadge(F.not_supported).label, 'Not supported');
});

test('nothing to show when there is no audit', () => {
  for (const bad of [null, undefined, {}, 'x']) {
    assert.equal(claimAuditBadge(bad).show, false);
  }
});

test('summary reports what was settled without conflating it with what was not', () => {
  const line = claimAuditSummaryLine({ total: 4, checked: 2, adverse: 1, inconclusive: 2 });
  assert.match(line, /2 of 4 citations checked/);
  assert.match(line, /1 flagged as unsupported/);
  assert.match(line, /2 could not be checked/);
});

test('a clean run does not claim more than it checked', () => {
  const line = claimAuditSummaryLine({ total: 3, checked: 3, adverse: 0, inconclusive: 0 });
  assert.match(line, /none flagged as unsupported/);
  assert.doesNotMatch(line, /could not be checked/);
});

test('no summary when nothing was audited', () => {
  assert.equal(claimAuditSummaryLine({ total: 0 }), '');
  assert.equal(claimAuditSummaryLine(null), '');
});
