/**
 * tests/js/signalHelpers.test.mjs — the canonical signal renderer.
 *
 * The fixtures are NOT hand-written. They are generated by serialising real
 * Signals from research_companion/signals.py (see fixtures_signals.json), so
 * these tests fail if the Python model and this renderer ever disagree about
 * what a state means. Hand-written fixtures would only test my assumptions
 * about the payload — the mistake that shipped four defects in the walkthrough.
 *
 * Run: node --test tests/js/signalHelpers.test.mjs
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  signalBadge, groupSignals, signalSummaryLine, HEURISTIC_DISCLAIMER,
} from '../../research_companion/lab/static/js/signalHelpers.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const F = JSON.parse(fs.readFileSync(path.join(HERE, 'fixtures_signals.json'), 'utf8'));

// ---------------------------------------------------------------------------
// The states that must never read as a pass
// ---------------------------------------------------------------------------

test('a degraded check is muted, never a problem and never clean', () => {
  const b = signalBadge(F.degraded);
  assert.equal(b.label, 'Could not check');
  assert.equal(b.tone, 'muted');
  assert.equal(b.isAdverse, false, 'an outage is not a finding about the work');
  assert.equal(b.isClean, false);
  assert.equal(b.needsAttention, true);
});

test('a degraded badge says WHY, from the structured reason', () => {
  assert.match(signalBadge(F.degraded).title, /source could not be reached/);
});

test('not-checked is muted and demands attention', () => {
  const b = signalBadge(F.not_checked);
  assert.equal(b.label, 'Not checked');
  assert.equal(b.isClean, false);
  assert.equal(b.needsAttention, true);
  assert.match(b.title, /switched off in Settings/);
});

test('not-applicable is neither a pass nor a task', () => {
  const b = signalBadge(F.not_applicable);
  assert.equal(b.label, 'Not applicable');
  assert.equal(b.isClean, false, 'must not read as verified');
  assert.equal(b.needsAttention, false, 'and must not invent work');
  assert.equal(b.tone, 'muted');
});

// ---------------------------------------------------------------------------
// Completed checks
// ---------------------------------------------------------------------------

test('a completed deterministic check reads as verified', () => {
  const b = signalBadge(F.clean_deterministic);
  assert.equal(b.label, 'Verified');
  assert.equal(b.tone, 'ok');
  assert.equal(b.isClean, true);
});

test('a completed deterministic failure reads as a problem', () => {
  const b = signalBadge(F.adverse_deterministic);
  assert.equal(b.label, 'Problem found');
  assert.equal(b.tone, 'warn');
  assert.equal(b.isAdverse, true);
});

test('a matched heuristic is advisory, never a definitive problem', () => {
  // Mirrors Signal.label(), which checks the epistemic class BEFORE the
  // finding for exactly this reason.
  const b = signalBadge(F.heuristic_flagged);
  assert.match(b.label, /advisory/i);
  assert.doesNotMatch(b.label, /^Problem found$/);
  assert.equal(b.title, HEURISTIC_DISCLAIMER);
  assert.equal(b.isHeuristic, true);
});

test('an unmatched heuristic is also labelled advisory', () => {
  assert.match(signalBadge(F.heuristic_clear).label, /advisory/i);
});

// ---------------------------------------------------------------------------
// The renderer must not re-derive the rules
// ---------------------------------------------------------------------------

test('flags come from the backend, not from local logic', () => {
  // A payload whose flags contradict a naive reading of status/finding: the
  // renderer must follow the flags, because Python enforces the invariants and
  // a second implementation here would drift.
  const b = signalBadge({
    check_status: 'checked', finding: 'contradicted',
    epistemic_class: 'deterministic_fact',
    is_clean: false, is_adverse: true, needs_attention: true, detail: 'x',
  });
  assert.equal(b.isAdverse, true);
  assert.equal(b.needsAttention, true);
});

test('a missing or malformed signal renders nothing rather than guessing', () => {
  for (const bad of [null, undefined, {}, 'nope', 42, { finding: 'supported' }]) {
    assert.equal(signalBadge(bad).show, false);
  }
});

// ---------------------------------------------------------------------------
// Grouping — by actionability, not by outcome
// ---------------------------------------------------------------------------

const ALL = Object.values(F);

test('grouping separates not-applicable from needs-review', () => {
  const g = groupSignals(ALL);
  assert.equal(g.notApplicable.length, 1);
  assert.ok(g.needsReview.every(s => s.check_status !== 'not_applicable'),
    'a check that cannot apply is not an outstanding task');
});

test('adverse findings are counted separately from incomplete checks', () => {
  const g = groupSignals(ALL);
  assert.equal(g.needsAttention.length, 2, 'one deterministic, one heuristic');
  assert.equal(g.needsReview.length, 2, 'degraded + not_checked');
  assert.equal(g.clean.length, 2);
  assert.equal(g.total, ALL.length);
});

test('every signal lands in exactly one group', () => {
  const g = groupSignals(ALL);
  const counted = g.needsAttention.length + g.needsReview.length
    + g.notApplicable.length + g.clean.length;
  assert.equal(counted, g.total);
});

test('grouping never throws on rubbish', () => {
  for (const bad of [null, undefined, 'x', [null, 3, {}]]) {
    assert.ok(groupSignals(bad).total >= 0);
  }
});

// ---------------------------------------------------------------------------
// Summary — counts, never a score
// ---------------------------------------------------------------------------

test('the summary reports counts and never a composite score', () => {
  const line = signalSummaryLine(ALL);
  assert.match(line, /2 issues requiring attention/);
  assert.match(line, /2 checks could not be completed/);
  assert.match(line, /not applicable/);
  // A percentage would collapse "problem found" and "could not run" into one
  // number, which is the distinction the whole model preserves.
  assert.doesNotMatch(line, /%/);
});

test('the summary is empty when there is nothing to report', () => {
  assert.equal(signalSummaryLine([]), '');
  assert.equal(signalSummaryLine(null), '');
});

test('a fully clean set says so without hedging', () => {
  const line = signalSummaryLine([F.clean_deterministic, F.heuristic_clear]);
  assert.match(line, /2 passed/);
  assert.doesNotMatch(line, /requiring attention/);
});
