"""Deep-Research Report Export -- markdown serialization (Phase 2, slice 2e-5).

Lets the researcher save/share a generated deep-research report as a plain
markdown file: topic, per-question answer + citations (with an inline RCS
badge as text when scored), per-section and overall coverage, unverified-
quote caveats, and a footer restating that RCS/coverage are AI heuristics,
not verified/ground truth -- so an exported .md is no more "verified" than
the live Report view (views/report.js). Pure, no I/O, isinstance-guarded on
every nested field -- a malformed/partial/None report degrades to a
best-effort (or empty) string; this module NEVER raises. Mirrors
notes_store.notes_to_markdown's shape: a pure list-of-lines -> "\\n".join
builder over an already-built artifact. NO new LLM prompt -- this is
serialization of deep_research.build_report's output (plus the 2e-2 rcs /
2e-3 coverage / 2e-4 plan additions), never generation.

See docs/superpowers/specs/2026-08-10-report-export-design.md.
"""
from __future__ import annotations

from typing import Any

_RCS_CAVEAT = "Relevance & stance are AI judgments of the cited passage — not independently verified."
_COVERAGE_CAVEAT = (
    "Coverage is a BM25 heuristic — relative to what our own search judged "
    "relevant to each question, not ground truth."
)
_GENERIC_CAVEAT = (
    "Generated by Research Companion — citations are real library passages; "
    "AI judgments (relevance/stance/coverage) are heuristics, not ground truth."
)


def _citation_line(citation: Any) -> str | None:
    """One `- ` bullet for a single citation: paper_title + a locator
    (section_id / char range), plus an inline RCS badge-as-text,
    `_[relevance NN%, stance]_`, when citation.get("rcs") is a dict
    (mirrors views/report.js's badge: relevance*100 + stance). A non-dict
    citation returns None (skipped entirely by the caller -- never
    fabricated). Never raises."""
    if not isinstance(citation, dict):
        return None
    title = str(citation.get("paper_title") or "").strip() or "Untitled"
    section_id = str(citation.get("section_id") or "").strip()
    char_start = citation.get("char_start", 0)
    char_start = char_start if isinstance(char_start, int) else 0
    char_end = citation.get("char_end", 0)
    char_end = char_end if isinstance(char_end, int) else 0
    locator = (f"{section_id}, chars {char_start}–{char_end}"
               if section_id else f"chars {char_start}–{char_end}")

    line = f"- {title} — {locator}"

    rcs = citation.get("rcs")
    if isinstance(rcs, dict):
        relevance = rcs.get("relevance", 0.0)
        try:
            relevance = float(relevance)
        except (TypeError, ValueError):
            relevance = 0.0
        relevance = max(0.0, min(1.0, relevance))
        stance = rcs.get("stance")
        stance = stance if stance in ("supports", "contradicts", "neutral") else "neutral"
        line += f" — _[relevance {round(relevance * 100)}%, {stance}]_"

    return line


def _section_lines(section: Any) -> list[str]:
    """Lines for one report section: `## {question}`, the answer, a
    `**Citations**` bullet list (one bullet per citation, a placeholder
    line when there are none), an optional per-section coverage line, an
    optional unverified-quotes callout, and an optional error line. A
    non-dict *section* yields no lines (skipped entirely by the caller --
    never fabricated). Never raises."""
    if not isinstance(section, dict):
        return []

    question = str(section.get("question") or "").strip() or "Untitled question"
    answer = str(section.get("answer") or "")

    lines = [f"## {question}", "", answer, "", "**Citations**"]

    citations = section.get("citations")
    citations = citations if isinstance(citations, list) else []
    citation_lines = [ln for ln in (_citation_line(c) for c in citations) if ln]
    lines.extend(citation_lines if citation_lines else ["- _No citations._"])
    lines.append("")

    coverage = section.get("coverage")
    if isinstance(coverage, dict):
        pct = coverage.get("pct", 0)
        pct = pct if isinstance(pct, (int, float)) else 0
        cited = coverage.get("cited", 0)
        cited = cited if isinstance(cited, (int, float)) else 0
        relevant_available = coverage.get("relevant_available", 0)
        relevant_available = relevant_available if isinstance(relevant_available, (int, float)) else 0
        lines.append(f"_Coverage: {pct}% ({cited}/{relevant_available})_")
        lines.append("")

    unverified_quotes = section.get("unverified_quotes")
    unverified_quotes = unverified_quotes if isinstance(unverified_quotes, list) else []
    quotes = [q for q in unverified_quotes if isinstance(q, str) and q]
    if quotes:
        lines.append(f"Unverified quote(s) (not found verbatim in your library): {'; '.join(quotes)}")
        lines.append("")

    error = section.get("error")
    if isinstance(error, str) and error:
        lines.append(f"_Error: {error}_")
        lines.append("")

    return lines


def report_to_markdown(report: dict) -> str:
    """Pure serializer: report dict -> a markdown document. isinstance-
    guarded on every nested field -- a malformed/partial/None report never
    raises, degrading to a best-effort (or minimal/empty) string. Markdown
    is a downloaded file, never inserted into the DOM -- no HTML-escaping
    is needed here (that is a frontend Blob-download concern, not this
    serializer's).

    Order: `# {topic}` (fallback `# Deep-Research Report` when topic is
    empty); an overall `> **Coverage:** ...` line when report["coverage"]
    is a dict; per section a `## {question}` heading, the answer, a
    **Citations** bullet list (with an inline RCS-as-text badge when
    present), a per-section coverage line, an unverified-quotes callout,
    and an error line; a footer carrying the RCS caveat (only if any
    citation anywhere carries an `rcs` dict), the coverage caveat (only if
    report-level `coverage` is present), and a generic
    heuristics-not-ground-truth line -- so the exported file is no more
    "verified" than the live UI. Never raises: the whole body is wrapped in
    a defensive try/except returning "" as a last-resort fallback, mirroring
    coverage.score_report's/rcs.score_report's own outer guard.
    """
    try:
        if not isinstance(report, dict):
            return ""

        topic = str(report.get("topic") or "").strip()
        lines = [f"# {topic}" if topic else "# Deep-Research Report", ""]

        coverage = report.get("coverage")
        has_report_coverage = isinstance(coverage, dict)
        if has_report_coverage:
            pct = coverage.get("pct", 0)
            pct = pct if isinstance(pct, (int, float)) else 0
            median_pct = coverage.get("median_pct", pct)
            median_pct = median_pct if isinstance(median_pct, (int, float)) else pct
            cited = coverage.get("cited", 0)
            cited = cited if isinstance(cited, (int, float)) else 0
            relevant_available = coverage.get("relevant_available", 0)
            relevant_available = relevant_available if isinstance(relevant_available, (int, float)) else 0
            lines.append(
                f"> **Coverage:** {pct}% (median {median_pct}%) — "
                f"{cited}/{relevant_available} relevant passages cited"
            )
            lines.append("")

        sections = report.get("sections")
        sections = sections if isinstance(sections, list) else []

        has_rcs = False
        for section in sections:
            if not isinstance(section, dict):
                continue
            citations = section.get("citations")
            citations = citations if isinstance(citations, list) else []
            if any(isinstance(c, dict) and isinstance(c.get("rcs"), dict) for c in citations):
                has_rcs = True
                break

        for section in sections:
            lines.extend(_section_lines(section))

        lines.append("---")
        lines.append("")
        if has_rcs:
            lines.append(f"_{_RCS_CAVEAT}_")
        if has_report_coverage:
            lines.append(f"_{_COVERAGE_CAVEAT}_")
        lines.append(f"_{_GENERIC_CAVEAT}_")

        return "\n".join(lines) + "\n"
    except Exception:
        return ""
